
x-configs: &app-env
    env_file: .env
  
services:
  
  kafka:
    image: brayandevzn/mcp_sender:kafka-alpine
    container_name: kafka
    build:
      context: .
      dockerfile: Dockerfile.kafka

    
  base:
    image: brayandevzn/mcp_sender:base-alpine
    <<: *app-env
    
  consumer:
    <<: *app-env
    container_name: consumer
    build:
      context: .
      dockerfile: Dockerfile.consumer

    image: brayandevzn/mcp_sender:consumer-alpine
    depends_on:
    
      
      kafka:
        condition: service_healthy

      base:
        condition: service_started

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379

  api:

    image: brayandevzn/mcp_sender:api-alpine
    build:
      context: .
      dockerfile: Dockerfile.api

    container_name: api

    ports:
      - 8000:8000
    <<: *app-env

    depends_on:
      kafka:
        condition: service_healthy

      base:
        condition: service_started
      
      redis:
        condition: service_started

      consumer:
        condition: service_started
          

      

      

  

  

  

  